kind: DataSetConfiguration
apiVersion: client.emporous.io/v1alpha1
collection:
  linkedCollections:
    - localhost:5001/test:latest
  schemaAddress: localhost:5001/schema:latest
  files:
    - file: "*.jpg"
      attributes:
        animal: "fish"
        habitat: "ocean"
        size: "small"
        color: "blue"
    - file: "level1/file.txt"
      attributes:
        genre: "science fiction"
        bool: true
    - file: "fish.jpg"
      attributes:
        size: "large"
